version: "3.8"

# Herda as configurações base de rede e volumes
volumes:
  postgres_data:
    name: orion_postgres_data_dev
  mongo_data:
    name: orion_mongo_data_dev

networks:
  orion_network:
    driver: bridge

services:
  # Base para o ambiente de desenvolvimento
  db_postgres:
    image: postgres:16-alpine
    container_name: orion_postgres_db_dev
    environment:
      POSTGRES_USER: orion_user
      POSTGRES_PASSWORD: orion_password
      POSTGRES_DB: orion_db
    ports:
      - "5432:5432"
    volumes:
      # Monta volume local para persistência em Dev
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "orion_user", "-d", "orion_db"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - orion_network

  db_mongo:
    image: mongo:latest
    container_name: orion_mongo_db_dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: orion_admin
      MONGO_INITDB_ROOT_PASSWORD: orion_admin_pass
    ports:
      - "27017:27017"
    volumes:
      # Monta volume local para persistência Dev
      - mongo_data:/data/db_mongo
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ping: 1})"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - orion_network
